// src/utils/emojiMap.js
export const emojiKeywords = {
    // TRAVAIL & CARRIÈRE - WORK & CAREER
    // Général - General
    'work': '💼',
    'travail': '💼',
    'travailler': '💼',
    'boulot': '💼',
    'job': '💼',
    'emploi': '💼',
    'bureau': '🏢',
    'office': '🏢',
    'business': '💼',
    'entreprise': '💼',
    'société': '💼',
    'carrière': '📈',
    'career': '📈',
    'métier': '💼',
    'profession': '💼',
  
    // Réunions & Communication - Meetings & Communication
    'meeting': '👥',
    'réunion': '👥',
    'appel': '📞',
    'call': '📞',
    'visio': '🎥',
    'zoom': '🎥',
    'teams': '👥',
    'conférence': '🎤',
    'conference': '🎤',
    'présentation': '📊',
    'presentation': '📊',
    'pitch': '🎯',
    'entretien': '🤝',
    'interview': '🤝',
    'client': '🤝',
    'feedback': '💭',
    'retour': '💭',
    'avis': '💭',
  
    // Email & Messages
    'email': '📧',
    'mail': '📨',
    'courriel': '📧',
    'messagerie': '📥',
    'inbox': '📥',
    'boîte': '📥',
    'message': '💬',
    'répondre': '↩️',
    'reply': '↩️',
    'envoyer': '📤',
    'send': '📤',
    'discuter': '💭',
    'chat': '💭',
    'discussion': '💭',
    'slack': '💬',
    'discord': '🎮',
  
    // Tâches & Projets - Tasks & Projects
    'projet': '📋',
    'project': '📋',
    'tâche': '✅',
    'task': '✅',
    'deadline': '⏰',
    'échéance': '⏰',
    'urgent': '🚨',
    'priorité': '⚡',
    'priority': '⚡',
    'rapport': '📊',
    'report': '📊',
    'révision': '👀',
    'review': '👀',
    'éditer': '✍️',
    'edit': '✍️',
    'brouillon': '📝',
    'draft': '📝',
    'planification': '📅',
    'planning': '📅',
    'feuille de route': '🗺️',
    'roadmap': '🗺️',
    'étape': '🏁',
    'milestone': '🏁',
  
    // Tech & Dev
    'code': '👨‍💻',
    'coder': '👨‍💻',
    'programmer': '👨‍💻',
    'développer': '👨‍💻',
    'développement': '👨‍💻',
    'bug': '🐛',
    'bogue': '🐛',
    'débug': '🔍',
    'debug': '🔍',
    'test': '🧪',
    'tester': '🧪',
    'déployer': '🚀',
    'deploy': '🚀',
    'mise à jour': '🔄',
    'update': '🔄',
    'sauvegarde': '💾',
    'backup': '💾',
    'site': '🌐',
    'website': '🌐',
    'application': '📱',
    'app': '📱',
    'base de données': '🗄️',
    'database': '🗄️',
    'serveur': '🖥️',
    'server': '🖥️',
    'cloud': '☁️',
    'nuage': '☁️',
  
    // Créatif & Design - Creative & Design
    'design': '🎨',
    'conception': '🎨',
    'créatif': '🎯',
    'creative': '🎯',
    'maquette': '🖼️',
    'mockup': '🖼️',
    'prototype': '🛠️',
    'esquisse': '✏️',
    'sketch': '✏️',
    'illustrer': '🖌️',
    'illustrate': '🖌️',
    'logo': '➰',
    'marque': '™️',
    'brand': '™️',
    'couleur': '🎨',
    'color': '🎨',
    'police': '🔤',
    'font': '🔤',
  
    // TÂCHES QUOTIDIENNES - DAILY TASKS
    // Maison - Home
    'nettoyer': '🧹',
    'clean': '🧹',
    'nettoyage': '🧹',
    'cleaning': '🧹',
    'aspirer': '🧵',
    'vacuum': '🧵',
    'lessive': '🧺',
    'laundry': '🧺',
    'vaisselle': '🍽️',
    'dishes': '🍽️',
    'poubelle': '🗑️',
    'trash': '🗑️',
    'déchets': '🗑️',
    'garbage': '🗑️',
    'recycler': '♻️',
    'recycle': '♻️',
    'organiser': '📦',
    'organize': '📦',
    'ranger': '🧹',
    'réparer': '🔧',
    'repair': '🔧',
    'bricoler': '🛠️',
    'fix': '🛠️',
    'entretien': '🔧',
    'maintenance': '🔧',
  
    // Cuisine & Alimentation - Cooking & Food
    'cuisiner': '👨‍🍳',
    'cook': '👨‍🍳',
    'cuisine': '🍳',
    'cooking': '🍳',
    'préparer': '🔪',
    'prepare': '🔪',
    'repas': '🍽️',
    'meal': '🍽️',
    'petit-déjeuner': '🍳',
    'breakfast': '🍳',
    'déjeuner': '🥪',
    'lunch': '🥪',
    'dîner': '🍽️',
    'dinner': '🍽️',
    'courses': '🛒',
    'groceries': '🛒',
    'shopping': '🛍️',
    'acheter': '🛍️',
    'buy': '🛍️',
    'nourriture': '🍴',
    'food': '🍴',
    'recette': '📖',
    'recipe': '📖',
    'restaurant': '🍽️',
  
    // SANTÉ & BIEN-ÊTRE - HEALTH & WELLNESS
    // Sport & Fitness
    'sport': '💪',
    'gym': '💪',
    'musculation': '🏋️',
    'workout': '🏋️',
    'exercice': '🤸',
    'exercise': '🤸',
    'courir': '🏃',
    'run': '🏃',
    'course': '🏃‍♂️',
    'running': '🏃‍♂️',
    'marcher': '🚶',
    'walk': '🚶',
    'nager': '🏊',
    'swim': '🏊',
    'vélo': '🚲',
    'bike': '🚲',
    'cyclisme': '🚲',
    'cycling': '🚲',
    'yoga': '🧘‍♀️',
    'étirer': '🤸‍♀️',
    'stretch': '🤸‍♀️',
    'entraînement': '💪',
    'training': '💪',
    'cardio': '❤️',
    'fitness': '🎯',
  
    // Santé - Health
    'médecin': '👨‍⚕️',
    'doctor': '👨‍⚕️',
    'docteur': '👨‍⚕️',
    'médical': '🏥',
    'medical': '🏥',
    'dentiste': '🦷',
    'dentist': '🦷',
    'examen': '🩺',
    'checkup': '🩺',
    'rendez-vous': '📅',
    'appointment': '📅',
    'médicament': '💊',
    'medicine': '💊',
    'pharmacie': '💊',
    'pharmacy': '💊',
    'santé': '❤️',
    'health': '❤️',
    'thérapie': '🧠',
    'therapy': '🧠',
    'massage': '💆‍♂️',
  
    // Bien-être Mental - Mental Wellness
    'méditer': '🧘',
    'meditate': '🧘',
    'méditation': '🧘‍♂️',
    'meditation': '🧘‍♂️',
    'pleine conscience': '🧠',
    'mindful': '🧠',
    'relaxer': '😌',
    'relax': '😌',
    'repos': '😴',
    'rest': '😴',
    'dormir': '💤',
    'sleep': '💤',
    'sieste': '😴',
    'nap': '😴',
    'journal': '📔',
    'diary': '📔',
  
    // FINANCES & ADMINISTRATION
    'payer': '💳',
    'pay': '💳',
    'paiement': '💰',
    'payment': '💰',
    'facture': '💵',
    'bill': '💵',
    'banque': '🏦',
    'bank': '🏦',
    'argent': '💰',
    'money': '💰',
    'budget': '💹',
    'dépense': '💸',
    'expense': '💸',
    'impôts': '📊',
    'taxes': '📊',
    'documents': '📄',
    'papiers': '📄',
    'formulaire': '📝',
    'form': '📝',
    'signer': '✍️',
    'sign': '✍️',
    'contrat': '📜',
    'contract': '📜',
    'assurance': '🔒',
    'insurance': '🔒',
  
    // TRANSPORTS - TRANSPORTATION
    'vol': '✈️',
    'flight': '✈️',
    'avion': '✈️',
    'plane': '✈️',
    'train': '🚂',
    'bus': '🚌',
    'métro': '🚇',
    'metro': '🚇',
    'taxi': '🚕',
    'voiture': '🚗',
    'car': '🚗',
    'conduire': '🚗',
    'drive': '🚗',
  
    // ÉVÉNEMENTS & SOCIAL - EVENTS & SOCIAL
    'fête': '🎉',
    'party': '🎉',
    'anniversaire': '🎂',
    'birthday': '🎂',
    'mariage': '💒',
    'wedding': '💒',
    'célébration': '🎊',
    'celebration': '🎊',
    'rencontrer': '🤝',
    'meet': '🤝',
    'café': '☕',
    'coffee': '☕',
    'boire': '🍻',
    'drinks': '🍻',
    'rendez-vous': '❤️',
    'date': '❤️',
    'amis': '👥',
    'friends': '👥',
    'famille': '👨‍👩‍👦',
    'family': '👨‍👩‍👦',
  
    // LOISIRS - HOBBIES
    'film': '🎬',
    'movie': '🎬',
    'cinéma': '🎦',
    'cinema': '🎦',
    'théâtre': '🎭',
    'theatre': '🎭',
    'concert': '🎵',
    'spectacle': '🎪',
    'show': '🎪',
    'jeu': '🎮',
    'game': '🎮',
    'jouer': '🎲',
    'play': '🎲',
    'lire': '📚',
    'read': '📚',
    'livre': '📖',
    'book': '📖',
    'musique': '🎵',
    'music': '🎵',
  
    // Par défaut - Default
    'default': '📌'
  };
  
  export function findEmoji(text) {
    if (!text) return emojiKeywords.default;
    
    text = text.toLowerCase();
    
    // Cherche le mot clé le plus long qui correspond
    let matchedEmoji = emojiKeywords.default;
    let longestMatch = 0;
    
    for (const [keyword, emoji] of Object.entries(emojiKeywords)) {
      if (text.includes(keyword) && keyword.length > longestMatch) {
        matchedEmoji = emoji;
        longestMatch = keyword.length;
      }
    }
    
    return matchedEmoji;
  }
  